---
title: "WGCNA of exoRNA samples & generation of Suppl. File 2,4"
subtitle: "Data of Li et al. https://doi.org/10.1093/nar/gkx891"
author: "Aram Safrastyan"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: 
    keep_md: yes
    toc: TRUE
    code_folding: hide
    number_sections: TRUE
---

<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r global_options, echo = F}
knitr::opts_chunk$set(fig.path='markdown_results/')
```

# load libraries
***

```{r libraries, message=F, warning=F}
library(forcats)
library(dplyr)
library(WGCNA)
library(cowplot)
library(ggplot2)
library(dendextend)
library(RColorBrewer)
library(tibble)
library(ggrepel)
library(tidyr)
library(ragg)
library(cowplot)
library(stringr)
library(org.Hs.eg.db)
library(clusterProfiler)
library(AnnotationDbi)
library(openxlsx)
```

# Data cleanup 
***

```{r clean, message=F, warning=F, fig.width= 15, fig.height=8}
#load gene expression matrix and metadata
load("./exorna/data/input/exorna_input.RData")
#check with WGCNA function if there are any bad samples or genes (e.g. too many missing values)
gsg <- goodSamplesGenes(exorna_wgcna)
gsg$allOK #no bad samples of genes detected
#for outlier detection hierarchical clustering is done
sampleTree <- hclust(dist(exorna_wgcna), method = "average")
#plot the results as a dendrogram 
plot(sampleTree, main = "Sample clustering to detect outliers", sub="", xlab="", cex.lab = 1.5, cex.axis = 1.5, cex.main = 2)
#based on dendrogram choose cutting height - the outlier samples to filter out 
clust <- cutreeStatic(sampleTree, cutHeight = 100, minSize = 2)
#examine the clusters - one should be very small and contain only the outlier samples
table(clust)
#choose only non-outlier samples
exorna_wgcna_input<-exorna_wgcna[clust==1, ]
#check data dimensions 
dim(exorna_wgcna_input)
```

# WGCNA 
## picking a power value
***

```{r power, warning=FALSE, message=FALSE, fig.width= 15, fig.height=8, fig.align='center'}
#use 8 threads 
enableWGCNAThreads(nThreads=8) 
#picking soft threshold power
powers <- c(c(1:10), seq(from = 12, to=20, by=2))
#calculate the fit to a scale-free network for different powers 
sft <- pickSoftThreshold(exorna_wgcna_input, powerVector = powers, networkType = "unsigned")
#plotting the results; plot 1
rsq<-ggplot(sft$fitIndices, aes(x=Power, y=(-sign(slope)*SFT.R.sq), label=Power)) + 
  geom_text(col="blue", size=10, family="Arial", fontface="bold") +
  ylab("Scale Free Topology Model Fit signed Rˆ2") +
  xlab("Soft Threshold (power)") + 
  geom_hline(yintercept = 0.85) + 
  theme_minimal(base_size = 26, base_family = "Arial") +
  theme(plot.title = element_text(color="black", size=28, face="bold", hjust = 0.5)) +
  ggtitle("Scale independence in exoRNA WGCNA")
#plot 2; mean connectivity (the mean of connections of genes in the network) generally should be about or below lower hundreds
conne<-ggplot(sft$fitIndices, aes(x=Power, y=mean.k., label=Power)) +
  geom_point(size=8) +
  scale_y_log10() + 
  xlab("Soft Threshold (power)") +
  ggtitle("Mean Connectivity") + 
  theme_minimal(base_size = 26, base_family = "Arial") +
  theme(plot.title = element_text(color="black", size=28, face="bold", hjust = 0.5)) +
  ggtitle("Mean connectivity in exoRNA WGCNA")
exorna_param<-ggdraw() + draw_plot(rsq, x=0, y=0, width = .5, height=1) + draw_plot(conne, x=0.5, y=0, width = .5, height=1) 
plot(exorna_param)
```

# main steps of WGCNA
* build adjacency matrix with the power value 
* calculate TOM and transform it to a disTOM
* hierarchical clustering
* merging similar modules
***

```{r modules, message=F, warning=F, fig.width= 15, fig.height=8, fig.align='center'}
#based on our results and WGCNS recommendations we choose a power value of 8
softPower<-8
#building an adjacency matrix
adjacency <- adjacency(exorna_wgcna_input, power = softPower, type = "unsigned")
#turn adjacency into topological overlap matrix (TOM) 
TOM <- TOMsimilarity(adjacency, TOMType = "unsigned")
#transformation into a dissimilarity measure 
dissTOM <- 1-TOM
# Call the hierarchical clustering function and use the dissimilarity measure 
geneTree <- hclust(as.dist(dissTOM), method = "average")
#we pick a minimal threshold of 30 genes per potential module 
minModuleSize <- 30
# Module identification using dynamic tree cut:
dynamicMods <- cutreeDynamic(dendro = geneTree, distM = dissTOM, minClusterSize = minModuleSize, deepSplit=2)
# Convert numeric labels into colors
dynamicColors <- labels2colors(dynamicMods)
#count the resulting modules
table(dynamicColors)
#calculate the module eigengenes (1st principal component of modules)
MEList <- moduleEigengenes(exorna_wgcna_input, colors = dynamicColors)
MEs <- MEList$eigengenes
#calculate dissimilarity of module eigengenes
MEDiss <- 1-cor(MEs)
#cluster module eigengenes
METree <- hclust(as.dist(MEDiss), method = "average")
#plot the result
d<-as.dendrogram(METree)
lab<-METree$labels[order.dendrogram(d)]
d<-color_labels(d ,labels=lab, col = sub("ME","",lab) )
par(mar=c(5,4,4,6)) 
plot(d, 
     main = "Clustering of module eigengenes", 
     horiz=T, 
     xlab = "", sub = "",cex=0.5)
#we pick a dissimilarity threshold of 0.2 (=correlation of 0.8) to merge very similar modules
MEDissThres <- 0.2
#plot the threshold line
abline(v=0.2, col=3)
#call an automatic merging function
merge <- mergeCloseModules(exorna_wgcna_input, dynamicColors, cutHeight = MEDissThres)
#merged module colors
exomergedcolors <- merge$colors
# get the eigengenes of the new merged modules
mergedMEs <- merge$newMEs
#plot the gene dendrogram to compare the old and new modules
plotDendroAndColors(geneTree, cbind(dynamicColors, exomergedcolors),
c("Dynamic Tree Cut", "Merged dynamic"),
dendroLabels = FALSE, hang = 0.03,
addGuide = TRUE, guideHang = 0.05)
n<-0
for (i in unique(exomergedcolors)){
n<-n+1
if (i=="grey") {
} else{
exomergedcolors[exomergedcolors==i]<-paste0("exo-", "", i)
} 
}
#get a list of new modules 
table(exomergedcolors)
#plot the new merged modules by size
df<-data.frame(dc=exomergedcolors) %>% 
  dplyr::count(dc) %>% mutate(col=str_remove(dc, "exo-"))
exorna_bar<-ggplot(df, aes(x=reorder(dc, n), y=n, fill=dc)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  scale_fill_manual(values = as.character(df$col)) +
  theme_minimal(base_size = 26, base_family = "Arial") +
  theme(legend.position = 'None', panel.grid.minor.y=element_blank(), panel.grid.major.y=element_blank(), axis.title=element_blank(), plot.title = element_text(color="black", size=28, face="bold", hjust = 0.5)) +
  ggtitle("Number of genes in exoRNA modules") +
  scale_y_continuous(expand = c(0, 0))
plot(exorna_bar)
#get the top hub gene of each module (most connected gene in a module)
chooseTopHubInEachModule(exorna_wgcna_input, exomergedcolors, power=softPower, type="unsigned")
#filter metadata appropriately (no outliers)
exorna_meta_input<-exorna_metadata[clust==1, ]
dir.create("./exorna/results/")
dir.create("./exorna/results/wgcna_main/")
save(exorna_wgcna_input, exorna_meta_input, exomergedcolors, exorna_param, exorna_bar, file="./exorna/results/wgcna_main/exowgcna.RData")
```

# Generation of Supplementary File 2
***

```{r supp_file2, warning=F, message=F}
#export 50 top hub genes per module based on absolute values of module membership
dataset_names <- list()
m <- 0
probes <- colnames(exorna_wgcna_input)
module <- unique(exomergedcolors)
module <- module[module != "grey"]
for (modules in module) {
  m <- m + 1
  inModule <- is.finite(match(exomergedcolors, modules))
  modProbes <- probes[inModule]
  IMConn <- softConnectivity(exorna_wgcna_input[, modProbes], type = "unsigned", power = 8)
  df_temp <- data.frame(genes=modProbes, module = modules, connectivity=IMConn)
  dataset_names[[m]] <- df_temp %>% top_n(., 50, connectivity) %>% arrange(., desc(connectivity))
}
write.xlsx(dataset_names, sheetName = module, file = './suppl_files/supplementary_file2.xlsx') 
```

# Generation of Supplementary File 4
***

```{r supp_file4, warning=F, message=F}
#GO Biological process enrichment analysis per module
dataset_path <- list()
x <- 0
module_genes<-data.frame(module = exomergedcolors, gene = colnames(exorna_wgcna_input)) 
module_genes_entrez<-AnnotationDbi::select(org.Hs.eg.db,
                              keys = module_genes$gene,
                              keytype = "SYMBOL",
                              columns = c("SYMBOL","ENTREZID")) %>% dplyr::left_join(module_genes,by=c("SYMBOL"="gene"))
for (modules in module) {
  x <- x + 1
  mod_genes <- module_genes_entrez %>% dplyr::filter(module==modules) %>% na.omit() %>%
    dplyr::select(ENTREZID) %>% unique()
  go <- enrichGO(gene = mod_genes$ENTREZID,
                OrgDb = org.Hs.eg.db,
                ont = "BP",
                readable = TRUE)
  go_df<-fortify(go, showCategory = 5) %>% 
    dplyr::select(., c(ID, Description, p.adjust, geneID, Count))
  rownames(go_df) <- NULL
  dataset_path[[x]] <- go_df
}
#export the top 10 results
write.xlsx(dataset_path, sheetName = module, file = './suppl_files/supplementary_file4.xlsx') 
```

```{r}
sessionInfo()
```
