---
title: "Generation of main Fig. 1"
subtitle: "Data of Zhu et al. https://doi.org/10.7150%2Fthno.48206"
author: "Aram Safrastyan"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: 
    keep_md: yes
    toc: TRUE
    code_folding: hide
    number_sections: TRUE
---

<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r global_options, echo = F}
knitr::opts_chunk$set(fig.path='markdown_results/')
```

# load libraries
***

```{r libraries, message=F, warning=F}
library(WGCNA)
library(dplyr)
library(cowplot)
library(ggplot2)
library(tibble)
library(ggrepel)
library(tidyr)
library(ragg)
library(scales)
library(forcats)
library(stringr)
library(openxlsx)
library(DT)
```

# Generation of Fig. 1A
***

```{r corr, warning=F, message=F, fig.width= 12, fig.height=10, fig.align='center'}
load("./cfrna/results/wgcna_main/cfwgcna.RData")
#get the gene and sample numbers of gene expression input
nGenes <- ncol(cfrna_wgcna_input)
nSamples <- nrow(cfrna_wgcna_input)
#get and order module eigengenes 
MEs0 <- moduleEigengenes(cfrna_wgcna_input, cfmergedcolors)$eigengenes
MEs <- orderMEs(MEs0)
#remove grey module which contains unassigned genes
MEs<- removeGreyME(MEs, greyMEName = paste(moduleColor.getMEprefix(), "grey", sep=""))
#correlate traits with modules 
moduleTraitCor <- cor(MEs, cfrna_meta_input, use = "p")
#get the p values
moduleTraitPvalue <- corPvalueStudent(moduleTraitCor, nSamples)
#FDR correction of p values
moduleTraitPvalue[ ,1] <- p.adjust(moduleTraitPvalue[ ,1], method = "fdr")
moduleTraitPvalue[ ,2] <- p.adjust(moduleTraitPvalue[ ,2], method = "fdr")
moduleTraitPvalue[ ,3] <- p.adjust(moduleTraitPvalue[ ,3], method = "fdr")
#to plot the results in ggplot some data wrangling needs to be done
module_trait_df<-as.data.frame(moduleTraitCor)
module_trait_df$modules<-gsub("ME", "", rownames(module_trait_df))
module_trait_long<-module_trait_df %>%  
  pivot_longer(!modules, names_to = "cor", values_to = "value") %>% 
  mutate(cor = fct_recode(cor, "disease state" = "disease_state"))
module_p_df<-as.data.frame(moduleTraitPvalue)
module_p_df$modules<-gsub("ME", "", rownames(module_p_df))
module_p_long<-module_p_df %>%  
  pivot_longer(!modules, names_to = "cor", values_to = "value") %>% 
  mutate(cor = fct_recode(cor, "disease state" = "disease_state"))
module_trait_long$modules<-factor(module_trait_long$modules, levels=c("cf-blue", "cf-purple", "cf-brown", "cf-red", "cf-magenta", "cf-black", "cf-yellow", "cf-turquoise"))
heatmap_core <- ggplot(module_trait_long, aes(x = cor, y = modules)) +
  geom_tile(color = "black", aes(fill = value)) + 
  scale_fill_distiller(palette = "RdBu") +
  labs(x = "", y = "", fill="cor") +
  scale_x_discrete(expand = c(0,0))+
  scale_y_discrete(expand = c(0,0)) + 
  theme(
    legend.title.align=0.5,
    legend.key = element_rect(fill = "lightblue", color = NA),
    legend.key.size = unit(2.5, "cm"),
    legend.key.width = unit(1.5,"cm") 
  ) 
heatmap_full <- heatmap_core + 
  geom_point(data = module_p_long, aes(x=cor, y=modules, size=-log10(value)), alpha=0.5) + 
  scale_size("-log10(p.adjust)", range=c(5, 20), breaks=c(5, 10, 25)) + 
  guides(size = guide_legend(reverse=T)) +   
  theme_bw(base_size = 17, base_family = "Arial", base_rect_size = 1, base_line_size = 1) +
  theme(plot.title = element_text(color="black", size=18, face="bold", hjust = 0.5), plot.subtitle = element_text(color="black", size=17, face="bold", hjust = 0.5)) +
  theme(legend.key=element_blank(), legend.key.height = unit(1, "cm"), legend.key.width = unit(1, "cm")) + 
  ggtitle("Module-trait relationships for cell-free RNA dataset", subtitle = ("(Zhu et al.)"))
print(heatmap_full)
```

# Generation of Fig. 1B,C
***

```{r mm, warning=F, message=F, fig.width= 10, fig.height=8, fig.align='center'}
#extract the cancer stage information
condition <- as.data.frame(cfrna_meta_input$disease_state)
names(condition) <- "Condition"
#names (colors) of the modules
modNames <- substring(names(MEs), 3)
#calculate the gene module membership and its significance 
geneModuleMembership <- as.data.frame(cor(cfrna_wgcna_input, MEs, use = "p"))
MMPvalue <- as.data.frame(corPvalueStudent(as.matrix(geneModuleMembership), nSamples))
names(geneModuleMembership) <- paste("MM", modNames, sep="")
names(MMPvalue) <- paste("p.MM", modNames, sep="")
#calculate the correlation and significance of gene-trait relationship
geneTraitSignificance <- as.data.frame(cor(cfrna_wgcna_input, condition, use = "p"))
GSPvalue <- as.data.frame(corPvalueStudent(as.matrix(geneTraitSignificance), nSamples))
names(geneTraitSignificance) <- paste("GS.", names(condition), sep="")
names(GSPvalue) <- paste("p.GS.", names(condition), sep="")
geneModuleMembership$trait<- geneTraitSignificance$GS.Condition
#choose the module with the highest negative correlation with disease condition
module="cf-blue"
column <- match(module, modNames)
moduleGenes <- cfmergedcolors==module
#plot the relationship between gene correlation with disease condition and gene module membership
blue<-geneModuleMembership %>%
  filter(moduleGenes) %>%
  rownames_to_column(., var = "genes") %>% {
  ggplot(., aes(x=`MMcf-blue`, y=trait))  +
  geom_point(size=2, color="blue", alpha=0.15)  +
  geom_smooth(method="lm", color="red") + 
  scale_x_continuous(limits = c(-1, 1))  + 
  scale_y_continuous(limits = c(-1, 1))  +  
  labs(x = "Module membership in cf-blue module", y = paste0("Gene-trait significance", "\n", "for disease state"), title="Module membership vs. gene significance", subtitle = "module cf-blue")  + 
       theme_classic(base_size = 17, base_family = "Arial") +
      theme(plot.title = element_text(color="black", size=18, face="bold", hjust = 0.5),
      plot.subtitle = element_text(color="black", size=17, face="bold", hjust = 0.5)) 
  }
blue
#choose the module with the highest positive correlation with disease condition
module="cf-turquoise"
column <- match(module, modNames)
moduleGenes <- cfmergedcolors==module
turq<-geneModuleMembership %>%
  filter(moduleGenes) %>%
  rownames_to_column(., var = "genes") %>% {
  ggplot(., aes(x=`MMcf-turquoise`, y=trait))  +
  geom_point(size=2, color="turquoise", alpha=0.15)  +
  geom_smooth(method="lm", color="red") + 
  scale_x_continuous(limits = c(-1, 1))  + 
  scale_y_continuous(limits = c(-1, 1))  + 
  labs(x = "Module membership in cf-turquoise module", y = paste0("Gene-trait significance", "\n", "for disease state"), title="Module membership vs. gene significance",  subtitle = "module cf-turquoise")  +
     theme_classic(base_size = 17, base_family = "Arial") +
      theme(plot.title = element_text(color="black", size=18, face="bold", hjust = 0.5),
       plot.subtitle = element_text(color="black", size=17, face="bold", hjust = 0.5)) 
  }
turq
```

# Generation of Fig. 1
***

```{r fig1, warning=F, message=F, fig.width= 15, fig.height=10, fig.align='center'}
fig1<-ggdraw() +
  draw_plot(heatmap_full, x = 0, y = 0, height=1, width=.55) +
  draw_plot(blue, x = .55, y = 0.5, width=.45, height = .5) +
  draw_plot(turq, x = .55, y = 0, width =.45, height = .5) +
  draw_plot_label(label = c("A", "B", "C"), size = 24,
                  x = c(0, 0.55, 0.55), y = c(0.98, 0.98, 0.48), family = "Arial")
fig1
dir.create("./figures/")
dir.create("./figures/main_figures/")
ggsave(plot=fig1, file="./figures/main_figures/fig1.png", units = "mm", device = ragg::agg_png, height=100, width=180, scaling = 0.445, limitsize = FALSE)
```

```{r}
sessionInfo()
```
