---
title: "Generation of main Fig. 3 and Supp. Fig. 4"
subtitle: "Data of Zhu et al. https://doi.org/10.7150%2Fthno.48206 & Li et al. https://doi.org/10.1093/nar/gkx891"
author: "Aram Safrastyan"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: 
    keep_md: yes
    toc: TRUE
    code_folding: hide
    number_sections: TRUE
---

<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>

# load libraries
***

```{r libraries, message=F, warning=F}
library(forcats)
library(dplyr)
library(WGCNA)
library(cowplot)
library(ggplot2)
library(RColorBrewer)
library(tibble)
library(ggrepel)
library(tidyr)
library(stringr)
library(cowplot)
```

# Module presevation calculation (cfRNA modules => exoRNA data)
***

```{r cfmp, eval=F, warning=F, message=F}
enableWGCNAThreads(nThreads=8) 
load("./cfrna/results/wgcna_main/cfwgcna.RData")
load("./exorna/results/wgcna_main/exowgcna.RData")
setLabels <- c("cfRNA", "exoRNA") 
multiExpr <- list(cfRNA = list(data = cfrna_wgcna_input), exoRNA = list(data = exorna_wgcna_input))
multiColor <- list(cfRNA = cfmergedcolors)
mp_cf_exo <- modulePreservation(multiExpr, multiColor, referenceNetworks = 1, nPermutations = 100, randomSeed = 1, quickCor = 0, maxModuleSize=5000, maxGoldModuleSize=5000, parallelCalculation=T)
```

# Generation of Figure 3 
***

```{r cfmp_plot, warning=F, message=F, fig.width= 8, fig.height=5, fig.align='center'}
load("./cfrna/results/mp_cf_exo/mp_cf_exo.RData")
#get module size and Zsum connectivity statistics 
ref <-  1
test <- 2
modColors <- rownames(mp_cf_exo$preservation$observed[[ref]][[test]])
moduleSizes <-  mp_cf_exo$preservation$Z[[ref]][[test]][, 1]
plotData <- cbind(mp_cf_exo$preservation$observed[[ref]][[test]][, 2], mp_cf_exo$preservation$Z[[ref]][[test]][, 2])
df<-as.data.frame(plotData)
df$mod<-modColors
df<-df[ , 2:3]
df$size<-moduleSizes
# leave grey and gold modules out
df_input<-df %>% 
  filter(!mod %in% c("gold", "grey")) %>% mutate(col=str_remove(mod, "cf-"))
rects <- data.frame(xstart = c(0, 2, 10), xend = c(2, 10, 100), col = letters[1:3])
mp1<-ggplot() + 
  geom_rect(data = rects, aes(xmin = xstart, xmax = xend, ymin = 0, ymax = 8000, fill=col), alpha = 0.15,) +  
  scale_fill_manual(values=c("darkgrey", "lightblue", "blue")) + 
  geom_point(data=df_input, aes(x=V2, y=size, colour=col), size=8, alpha=0.5) + 
  geom_vline(xintercept = 2, colour="red") + 
  geom_vline(xintercept = 10, colour="green") +
  theme_classic(base_size = 8) +  
  scale_colour_identity() +
  geom_label_repel(data = df_input,
                   aes(x=V2, y=size, label=mod),
                   box.padding   = 0.5, 
                   point.padding = 0.5,
                   segment.color = 'black',
                   max.overlaps = Inf,
                   size=2,
                   segment.size=0.5,force=50)  +
  scale_x_continuous(trans='pseudo_log', expand = c(0, 0), breaks=c(0, 2, 10, 30, 70)) +
  scale_y_continuous(trans='pseudo_log', expand = c(0, 0), breaks = c(0, 100, 300, 1000, 3000), limits = c(0, 8000)) +
  labs(x = "Module preservation (Zsum)", y = "Module size", title="Module preservation vs. module size", subtitle = "cell-free RNA modules in exosomal RNA dataset")  +
  theme(text=element_text(family="Arial"), plot.title = element_text(color="black", size=9, face="bold", hjust = 0.5), plot.subtitle = element_text(color="black", size=8, face="bold", hjust = 0.5), legend.position="none")
#get Zconnectiviy and Zdensity preservation statistics
mp_data<-data.frame(density=mp_cf_exo$preservation$Z$ref.cfRNA$inColumnsAlsoPresentIn.exoRNA$Zdensity.pres, connectivity=mp_cf_exo$preservation$Z$ref.cfRNA$inColumnsAlsoPresentIn.exoRNA$Zconnectivity.pres, modules= rownames(mp_cf_exo$preservation$observed[[ref]][[test]])) %>% 
  filter(., !(modules %in% c("grey", "gold")) ) %>% 
  mutate(col=str_remove(modules, "cf-"))
rects <- data.frame(xstart = c(-1, 2, 10, -1, -1, -1), xend = c(2, 10, 90, 90, 90, 90), ystart=c(0, 0, 0, 0, 2, 10) , yend=c(130, 130, 130, 2, 10, 130) , col = letters[1:6])
mp2<-ggplot() + 
  geom_rect(data = rects, aes(xmin = xstart, xmax = xend, ymin = ystart, ymax = yend, fill=col), alpha = 0.15,) +  
  scale_fill_manual(values=c("darkgrey", "lightblue", "blue", "grey", "lightblue", "blue")) +
  geom_point(data=mp_data, aes(x=density, y=connectivity, colour=col), size=8, alpha=0.5) +
  geom_vline(xintercept = 2, colour="red") + geom_vline(xintercept = 10, colour="green") +
  geom_hline(yintercept = 2, colour="red") + geom_hline(yintercept = 10, colour="green") +
  theme_classic(base_size = 8) +  scale_colour_identity() +scale_x_continuous(trans='pseudo_log', limits = c(-1,90), expand = c(0, 0), breaks=c(-1, 0, 2, 10, 30, 75)) +
  scale_y_continuous(trans='pseudo_log', limits = c(0,130), expand = c(0, 0), breaks = c(0, 2, 10, 30, 75)) +
  geom_label_repel(data = mp_data,
                   aes(x=density, y=connectivity, label=modules),
                   box.padding   = 0.5, 
                   point.padding = 0.5,
                   segment.color = 'black',
                   max.overlaps = Inf,
                   size=2,
                   segment.size=0.5,force=50)   +
  labs(x = "Module density preservation", y = "Module connectivity preservation", title="Module density vs. connectivity preservation", subtitle = "cell-free RNA modules in exosomal RNA dataset") +
  theme(text=element_text(family="Arial"), plot.title = element_text(color="black", size=9, face="bold", hjust = 0.5), plot.subtitle = element_text(color="black", size=8, face="bold", hjust = 0.5), legend.position="none")
#combine
fig3<-ggdraw(ylim=c(0.5, 1), clip = "on") +
  draw_plot(mp1, x = 0, y = 0.5, height=.5, width=.5) +
  draw_plot(mp2, x = .5, y = 0.5, height=.5, width = .5) +
  draw_plot_label(label = c("A", "B"), size = 12,
                  x = c(0, 0.5), y = c(1, 1), family = "Arial") 
fig3
ggsave(plot=fig3, "./figures/main_figuresfig3.png", scale=1, units = "mm", width=180, height=70)
```

# Module presevation calculation (exoRNA modules => cfRNA data)
***

```{r exomp, eval=F, warning=F, message=F}
enableWGCNAThreads(nThreads=8) 
setLabels <- c("exoRNA", "cfRNA")
multiExpr <- list(exorRNA = list(data = exorna_wgcna_input), cfRNA = list(data = cfrna_wgcna_input) )
multiColor <- list(exoRNA = exomergedcolors)
mp_exo_cf <- modulePreservation(multiExpr, multiColor, referenceNetworks = 1, nPermutations = 100, randomSeed = 1, quickCor = 0, maxModuleSize=5500, maxGoldModuleSize=5500, parallelCalculation=T)
```

# Generation of Supp. Figure 4
***

```{r exomp_plot, message=F, warning=F, fig.width= 8, fig.height=5, fig.align='center'}
load("./exorna/results/mp_exo_cf/mp_exo_cf.RData")
#get module size and Zsum connectivity statistics 
ref <-  1
test <- 2
modColors <- rownames(mp_exo_cf$preservation$observed[[ref]][[test]])
moduleSizes <-  mp_exo_cf$preservation$Z[[ref]][[test]][, 1]
plotData <- cbind(mp_exo_cf$preservation$observed[[ref]][[test]][, 2], mp_exo_cf$preservation$Z[[ref]][[test]][, 2])
df<-as.data.frame(plotData)
df$mod<-modColors
df<-df[ , 2:3]
df$size<-moduleSizes
# leave grey and gold modules out
df_input<- df %>% 
  filter(!mod %in% c("gold", "grey")) %>% 
  mutate(col=str_remove(mod, "exo-"))
rects <- data.frame(xstart = c(0, 2, 10), xend = c(2, 10, 100), col = letters[1:3])
supp_fig4<-ggplot() + 
  geom_rect(data = rects, aes(xmin = xstart, xmax = xend, ymin = 0, ymax = 8000, fill=col), alpha = 0.15,) +  
  scale_fill_manual(values=c("darkgrey", "lightblue", "blue")) + 
  geom_point(data=df_input, aes(x=V2, y=size, colour=col), size=8, alpha=0.5) + 
  geom_vline(xintercept = 2, colour="red") + 
  geom_vline(xintercept = 10, colour="green") +
  theme_classic(base_size = 8) +  
  scale_colour_identity() +
  geom_label_repel(data = df_input,
                   aes(x=V2, y=size, label=mod),
                   box.padding   = 0.5, 
                   point.padding = 0.5,
                   segment.color = 'black',
                   max.overlaps = Inf,
                   size=2,
                   segment.size=0.5,force=50)  +
  scale_x_continuous(trans='pseudo_log', expand = c(0, 0), breaks=c(0, 2, 10, 30, 70)) +
  scale_y_continuous(trans='pseudo_log', expand = c(0, 0), breaks = c(0, 100, 300, 1000, 3000), limits = c(0, 8000)) +
  labs(x = "Module preservation (Zsum)", y = "Module size", title="Module preservation vs. module size", subtitle = "exosome RNA modules in cell-free RNA dataset")  +
  theme(text=element_text(family="Arial"), plot.title = element_text(color="black", size=9, face="bold", hjust = 0.5), plot.subtitle = element_text(color="black", size=8, face="bold", hjust = 0.5), legend.position="none")
supp_fig4
ggsave(plot=supp_fig4, "./figures/supp_figures/supp_fig4.png", scale=1, units = "mm", width=180, height=100)
```

```{r}
sessionInfo()
```
