---
title: "WGCNA of HCC exRNA samples"
author: "Aram Safrastyan"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: 
    code_folding: hide
    number_sections: TRUE
params:
  cell_type: ""
---

<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>

# Gene co-expression analysis of plasma exRNA liver cancer data (*"Theranostics"*) through WGCNA
***

## load libraries
***

```{r, message=F, warning=F}
library(dplyr)
library(Seurat)
library(WGCNA)
library(cowplot)
library(ggplot2)
library(dendextend)
library(tibble)
library(purrr)
library(tidyr)
library(biomaRt)
library(pheatmap)
```

## data cleanup by DESeq2 VST of gene expression dataframe and filtering (>= 5 in 90% of samples)
***

```{r, warning=FALSE, message=FALSE, fig.width= 15, fig.height=8, results='hide', dev=c('png', 'pdf', 'svg', 'tiff')}
#use 7 threads
enableWGCNAThreads(nThreads=10) 
load("/data/mahlzeitlocal/aram/wgcna/liver_exrna/theranostics/ex_wgcna/wgcna_all_source_imp.RData")
vst_ex<-vst_hcc
exmerged<-mergedColors
load("/data/fass1/aram/sc/wgcna/macparland/liver_sc_filt.RData")
for (i in unique(metacell_seurat$cell_type)) {
cell<-i
metacell_subset<-subset(x = metacell_seurat, subset = cell_type %in% cell)
#metacell_subset<-subset(x = metacell_subset, subset = condition %in% "norm")
genes.use <- rownames(metacell_subset)
targets <- metacell_subset@meta.data
metacell_subset <- FindVariableFeatures(metacell_subset, nfeatures = 5000)
genes.keep <- VariableFeatures(metacell_subset)
datExpr <- as.data.frame(GetAssayData(metacell_subset, assay='RNA', slot='data')[genes.keep,])
vst_matrix<-datExpr
genes<-rownames(vst_matrix)
group_labels <- targets
vst_df <- t(as.data.frame(vst_matrix))
gsg <- goodSamplesGenes(vst_df)
gsg$allOK
vst_df<-vst_df[ , gsg$goodGenes]
vst_hcc<-vst_df
dim(vst_hcc)
httr::set_config(httr::config(ssl_verifypeer = FALSE))
#liver_matrix<-as.data.frame(t(vst_ex))

setLabels <- c("exRNA", "scRNA") 
multiExpr <- list(exRNA = list(data = vst_ex), scRNA = list(data = vst_hcc) )
multiColor <- list(exRNA = exmerged)

mp <- modulePreservation(multiExpr, multiColor, referenceNetworks = 1, nPermutations =100, randomSeed = 1, quickCor = 0, maxModuleSize=5000, maxGoldModuleSize=5000, parallelCalculation=T)
mp_norm<-mp
ref = 1 
test = 2 
statsObs = cbind(mp$quality$observed[[ref]][[test]][, -1], mp$preservation$observed[[ref]][[test]][, -1])
statsZ = cbind(mp$quality$Z[[ref]][[test]][, -1], mp$preservation$Z[[ref]][[test]][, -1]);

print( cbind(statsObs[, c("medianRank.pres", "medianRank.qual")], signif(statsZ[, c("Zsummary.pres", "Zsummary.qual")], 2)) )
qww<-cbind(statsObs[, c("medianRank.pres", "medianRank.qual")], signif(statsZ[, c("Zsummary.pres", "Zsummary.qual")], 2))
table(qww)
modColors = rownames(mp$preservation$observed[[ref]][[test]]) 
moduleSizes = mp$preservation$Z[[ref]][[test]][, 1]; 
# leave grey and gold modules out 
plotMods = !(modColors %in% c("grey", "gold")); 
# Text labels for points 
text = modColors[plotMods]; 
# Auxiliary convenience variable 
plotData = cbind(mp$preservation$observed[[ref]][[test]][, 2], mp$preservation$Z[[ref]][[test]][, 2]) 
# Main titles for the plot 
mains = c("Preservation Median rank", "Preservation Zsummary"); 
# Start the plot sizeGrWindow(10, 5); 
#pdf(fi="Plots/BxHLiverFemaleOnly-modulePreservation-Zsummary-medianRank.pdf", wi=10, h=5) 
par(mfrow = c(1,2)) 
par(mar = c(4.5,4.5,2.5,1)) 
for (p in 1:2) 
  { 
  min = min(plotData[, p], na.rm = TRUE); 
  max = max(plotData[, p], na.rm = TRUE); 
# Adjust ploting ranges appropriately 
  if (p==2) 
  { 
    if (min > -max/10) min = -max/10 
    ylim = c(min -0.1 * (max-min), max + 0.1 * (max-min)) 
    } else 
      ylim = c(max + 0.1 * (max-min), min -0.1 * (max-min)) 
    plot(moduleSizes[plotMods], plotData[plotMods, p], col = 1, bg = modColors[plotMods], pch = 21, 
         main = mains[p], 
         cex = 2.4, 
         ylab = mains[p], 
         xlab = "Module size", 
         log = "x", 
         ylim = ylim, 
         xlim = c(10, 2000), cex.lab = 1.2, cex.axis = 1.2, cex.main =1.4) 
    labelPoints(moduleSizes[plotMods], plotData[plotMods, p], text, cex = 1, offs = 0.08); 
# For Zsummary, add threshold lines 
    if (p==2) 
    { 
      abline(h=0) 
      abline(h=2, col = "blue", lty = 2) 
      abline(h=10, col = "darkgreen", lty = 2) 
    } 
    } 
statsZ_all<-statsZ
save(statsZ_all, file=paste0(cell, "_", "statsZ.RData"))
}
```

```{r}
sessionInfo()
```

